// Code generated by hertz generator.

package main

import (
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/viper"
	"os"
)

func InitLog() {
	// Log as JSON instead of the default ASCII formatter.
	log.SetFormatter(&log.JSONFormatter{})

	// Output to stdout instead of the default stderr
	// Can be any io.Writer, see below for File example
	log.SetOutput(os.Stdout)

	// Only log the warning severity or above.
	log.SetLevel(log.InfoLevel)

	log.SetReportCaller(true)
}

func InitConfig() {
	viper.SetConfigName("config") // name of config file (without extension)
	viper.SetConfigType("yaml")   // REQUIRED if the config file does not have the extension in the name
	viper.AddConfigPath("conf")   // optionally look for config in the working directory
	//fmt.Println("path", viper.getConfigFile())
	err := viper.ReadInConfig() // Find and read the config file
	if err != nil {             // Handle errors reading the config file
		panic(fmt.Errorf("fatal error config file: %w", err))
	}
}

func Init() {
	InitLog()
	InitConfig()
}

func main() {
	Init()
	h := server.Default(server.WithHostPorts("0.0.0.0:8888"))

	register(h)
	h.Spin()
}
