// Code generated by hertz generator.

package story_telling_backend

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _story_tellingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chapterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnovelchaptertitleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailvel_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getchapterdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _novelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnoveldetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchnovelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tellingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnoveltellingconfigMw() []app.HandlerFunc {
	// your code...
	return nil
}
